### ISSUE TITLE
APIGetter.py[line:167] ERROR retry: 1, Bad retcode: 

### ISSUE THREAD

**Issue by woshihoujinxin** [zpoint/idataapi-transform#1]
[](url)
![@BX870)MFQ5 65O{$KXAD2J](https://user-images.githubusercontent.com/3643467/55555244-6c0a7600-5717-11e9-9b0d-deb4515c3d1c.png)

**Comment by woshihoujinxin** [comment]
能给出从api转入redis 或文件的更详细的的demo么，为什么我这从来没导入成功过

**Comment by woshihoujinxin** [comment]
![T~@BTJCN%4TW `F0MTZ{ 8H](https://user-images.githubusercontent.com/3643467/55555342-a70ca980-5717-11e9-8d58-69654cb4a413.png)
我的API返回的结果是这样的!

**Comment by zpoint** [comment]
你好，这里的 API 解析模块 是专门对接对我们公司内部使用的标准制定的，其他的格式/数据库比如 mongDB/csv 等不受此限制

当前能解析的 API 返回的标准如下，传入第一页url开始访问,  访问第 n 页的时候url参数传入前一页返回的 pageToken字符串即可，翻页完成则返回一个状态码表示不需要继续翻页了，比如

**第一页访问:**

http://localhost:8888/comment/ctrip?id=6469336

![image](https://user-images.githubusercontent.com/18083296/55598742-e2928c80-5786-11e9-9ccd-195a93d2a8ca.png)

**第二页访问:**

http://localhost:8888/comment/ctrip?id=6469336&pageToken=2

![image](https://user-images.githubusercontent.com/18083296/55598765-081f9600-5787-11e9-9c37-20e620f09060.png)

**data 里面的元素如下所示，data 为一个列表，data 里面每个对象为字典**
![image](https://user-images.githubusercontent.com/18083296/55598797-2b4a4580-5787-11e9-9a43-58e5a593d415.png)

**翻到了最后一页, pageToken 为 null, hasNext 为 false，提示用户中止翻页**

http://localhost:8888/comment/ctrip?id=6469336&pageToken=155

![image](https://user-images.githubusercontent.com/18083296/55599014-42d5fe00-5788-11e9-9dd4-1183c96f3761.png)

**即使翻过了最后一页, 也返回无结果，提示用户中止翻页**

http://localhost:8888/comment/ctrip?id=6469336&pageToken=1000

![image](https://user-images.githubusercontent.com/18083296/55599046-6f8a1580-5788-11e9-8d80-5b765ceec2ae.png)

**Comment by zpoint** [comment]
这里按照上面的标准返回 API 转 redis 的代码, 再从 redis 转换到 xlsx 的代码示例


    import asyncio
    from idataapi_transform import ProcessFactory, GetterConfig, WriterConfig
    
    class Demo(object):
        async def demo2redis(self):
            # max_limit=100 表示从该API最多获取100条数据，是个粗略值
            getter_config = GetterConfig.RAPIConfig("http://localhost:8888/comment/ctrip?id=6469336&parent=hotel", max_limit=100)
            getter = ProcessFactory.create_getter(getter_config)
    
            writer_config = WriterConfig.WRedisConfig("test_key")
            with ProcessFactory.create_writer(writer_config) as redis_writer:
                async for items in getter:
                    # print(items)
                    await redis_writer.write(items)
    
        async def demo2csv(self):
            getter_config = GetterConfig.RRedisConfig("test_key")
            getter = ProcessFactory.create_getter(getter_config)
    
            writer_config = WriterConfig.WXLSXConfig("./test.xlsx")
            with ProcessFactory.create_writer(writer_config) as xlsx_writer:
                async for items in getter:
                    # print(items)
                    xlsx_writer.write(items)
    
    if __name__ == "__main__":
        loop = asyncio.get_event_loop()
        d = Demo()
        # 从 api 转到 redis
        loop.run_until_complete(d.demo2redis())
        # 从 redis 转到 xlsx
        loop.run_until_complete(d.demo2csv())

当然，涉及到了 API 就要按照前面的标准才能解析，如果你是从 es 或者 MongoDB 导出到 csv 或者互相导出，则不需要遵循任何标准，直接导出即可
