### ISSUE TITLE
【建议】导出CSV 格式数据时，列的顺序能固定吗？

### ISSUE THREAD

**Issue by wajika** [zpoint/idataapi-transform#12]
我是从ES 读取数据 导出为CSV格式，源数据schme是固定的，但是每次导出的CSV列顺序不一样，能用某种方法固定吗？

**Comment by zpoint** [comment]
读出来的时候字段数量和字段顺序也不是固定的?

导出的时候有个 headers 参数, 你如果传了应该能固定

**Comment by wajika** [comment]
> 读出来的时候字段数量和字段顺序也不是固定的?
> 
> 导出的时候有个 headers 参数, 你如果传了应该能固定

header 怎么用？ 你更新下readme把，减少猜测的时间:relaxed:

**Comment by zpoint** [comment]
命令行没有 headers 喔, 代码的方式创建 config 的时候可以传 headers

headers 默认情况下是从源数据里面自动生成的, 如果你传了就不从源数据里面生成, 所以你传的字段要覆盖源数据所有的字段才行喔

```python
csv_config = WriterConfig.WCSVConfig("./result.csv", headers=["头1", "头2", "头3"])
```

<img width="1122" alt="image" src="https://user-images.githubusercontent.com/18083296/165676736-eff23eb1-f101-4b8d-8a28-71764762f1f9.png">

**Comment by wajika** [comment]
idataapi-transform\idataapi_transform\DataProcess\Config\ConfigUtil\WriterConfig.py(26): 
class WCSVConfig(BaseWriterConfig):

我找到了你图片的位置，但是没明白 要怎么加
csv_config = WriterConfig.WCSVConfig("./result.csv", headers=["头1", "头2", "头3"])

**Comment by zpoint** [comment]
命令行的话暂不支持

不用管截图的代码, 用代码导入的方式写法如下

[es-to-csv](https://github.com/zpoint/idataapi-transform/blob/master/README_CN.md#es-to-csv)

**Comment by wajika** [comment]
> 命令行的话暂不支持
> 
> 不用管截图的代码, 用代码导入的方式写法如下
> 
> [es-to-csv](https://github.com/zpoint/idataapi-transform/blob/master/README_CN.md#es-to-csv)
为什么改代码不行？
代码最终执行不还是python module吗？

**Comment by zpoint** [comment]
改包的代码最终能运行但是不推荐, 那是一次性的改法喔
